/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ExportedKeyPair {
  public: Array<number>;
  secret: Array<number>;
}
export function generateElgamalKeypair(): ExportedKeyPair;
export function encryptVote(
  pubKeyBytes: Array<number>,
  choice: number,
  optionsCount: number
): Array<number>;
export function verifyVote(
  pubKeyBytes: Array<number>,
  vote: Array<number>,
  optionsCount: number
): void;
export function decryptResult(
  secretKey: Array<number>,
  rawResult: Array<number>
): Array<number>;
export function eccEncrypt(pk: Buffer, msg: Buffer): Buffer;
export function eccDecrypt(sk: Buffer, encrypted: Buffer): Buffer;
export interface ExportedKeyPair {
  public: string;
  secret: string;
}
export function generateRsaKeypair(): ExportedKeyPair;
export function sign(secretKeyPem: string, blindMsg: Buffer): Buffer;
export function verify(
  publicKeyPem: string,
  signatureBytes: Buffer,
  msgRandomizer: Buffer,
  msg: string
): boolean;
